apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-deploy
spec:
  replicas: 10
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hellow-world
    spec:
      containers:
      - name: hello-pod
        image: bbenetskyy/k8s-python-api:second
        ports:
        - containerPort: 80
