apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-deploy
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: hellow-world
    spec:
      containers:
      - name: hello-pod
        image: bbenetskyy/k8s-python-api:first
        ports:
        - containerPort: 80
